"""Add space catalog display metadata

Revision ID: 3806d2ad9b8c
Revises: f194c991d216
Create Date: 2026-08-06 02:15:21.097040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3806d2ad9b8c'
down_revision = 'f194c991d216'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column("spaces", sa.Column("slug", sa.String(length=180), nullable=True))
    op.add_column(
        "spaces", sa.Column("image_url", sa.String(length=2048), nullable=True)
    )
    op.add_column(
        "spaces", sa.Column("image_alt", sa.String(length=255), nullable=True)
    )
    op.add_column("spaces", sa.Column("rating", sa.Float(), nullable=True))

    op.execute("UPDATE spaces SET slug = 'legacy-space-' || id")
    op.execute(
        "UPDATE spaces SET slug = 'cyberjaya-community-library' "
        "WHERE name = 'Cyberjaya Community Library'"
    )
    op.execute(
        "UPDATE spaces SET slug = 'open-co-working-lounge' "
        "WHERE name = 'Open Co-working Lounge'"
    )
    op.execute(
        "UPDATE spaces SET slug = 'coffee-bean-tea-leaf-dpulze' "
        "WHERE name = 'Coffee Bean & Tea Leaf'"
    )

    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.alter_column("slug", existing_type=sa.String(length=180), nullable=False)
        batch_op.create_index(batch_op.f('ix_spaces_slug'), ['slug'], unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spaces_slug'))
        batch_op.drop_column('rating')
        batch_op.drop_column('image_alt')
        batch_op.drop_column('image_url')
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
